Spis treści
1. [[Miejsc
   + [[Koci most]]


Celem przygody jest zdobycie całej przekętej księgi
Księga została rozbita na karty i każda z nich jest obok przedmiotu wykonanego
ze stali meteorytowej, każdy daje możliwość by gracz zszedł 1k20 poniżej 0 w
poczytalności.

| Karta | potwor              | lokacja          |
|-------+---------------------+------------------|
|     1 | Sukub               | Sanatorium       |
|     2 | Wampira             | Biedne dzielnice |
|     3 | Ciasteczkowy potwor | ulica sezamkowa  |
|     4 | Kraken              | Oceania          |
|     5 | yeti                | Arktyka          |
|     6 | Mantykora           | Gdzieś u arabów  |
|     7 | Studnia             | pole farmeskie   |
|     8 |                     |                  |



<<Miejsca>>

<<Koci most>>
    Jedyna droga na przyklad do czesci magazynu w porcie, i tam jest duzo kotkow
* TODO wymyśleć 20 opisów kotów
aby te koty jakość obejść można:
    a) Grać na specjalnym ultradzwiękowym flecie (tylko koty to słyszą)
    b) Przynieść 3-4 duże ryby (jak z powrotem?)
    c) Powystrzelać koty, ale to jest głośne

<<Antarktyda>
        Gracze w tej lokacji walczą z Kolorem
        jedna z przeciwnosci poza mechnika zamarzania
        i smierci od tego. Będzie scena gdzie będzie
        im się wydawało że widzą tak samo liczną grupę
        (podobno zaginionych poszukiwaczy)
        ale będą sie tak na prawdę bić sami ze sobą
        https://www.reddit.com/r/callofcthulhu/comments/uyd2xr/mechanic_of_freezing_to_death/


<<Cmentarz na zadupiu>>
    Gracze szukają juz typa XY bo wiedzą że ma kawałek księgi
    Wśród grobów jest jeden
    Z wpisami
    John Warwick+14 IV 1912 *5 III 1886
    Żona Anna Warwick z domu Pentee  +14 IV 1912 *28 VI 1888
    Zgineli śmiercią tragiczną na morzu
    Rodzice typa zmarli 1918 1920 (3 i rok przed kampania)
    wazne jest W bo w panoramie firm czy czyms takim da sie znalezc
    gdzie miejszaja starsi córki...  [[Studnia][patrz studnia]] oni potwierdza ze z Córka mówiła że jej
    mąż ma przywieźć z Anglii jakieś artefakty stare (to czego szukają)
    Z tego wynika że to czego szukają jest we wraku Tytanica


    <<Postwory>>

    <<Wampir>>
        Je Hobo w NY, Był francuzem który przybył do stanów w XVII-XVIIIw są liczne zapisy o nim w księgach. ostatnie
        są z Miesięcznika "upiorne stany" słaba strona to fakt że jak mówic do niego po francusku to wychodzi z wampirycznego transu i na powrót staje się "człowiekiem"
        za dania nie ma regeneracji ale w chuj zywotnosci bo jest kamieniem



<<tytanic>>
    Że nie ma chuja zejść na 3km pod wodę gracze będą musili odprawić rytułał zamiany umysłow i wykożystać do tego ryboludzi jakoś...


    <<Szuczur z dzielnicy Hobo>>
         W dzielnicy Hobo jest typ co wygląda jak szczur.
         Jeśli gracze podjadą samochodem jakoś za dnia zaproponuje zakład na 5$,
         że da radę przed nimi dostać się do pompy. Oni jadą on biegnie.
         Przed jazdą dokładnie na mapie pokazuje im trasę. Przeciętny test nawigacji
         potwierdza że nie kłamie. Szczur ma Nawigację (tam) na 95 a akrobatykę na 75
         Gracz musi zdać nawigację i prowadzenie pojazdów. W przypadku remisu wygyrywa
         szczur. Niezależnie od wyniku Szczur proponuje graczom nauczyć ich sztuki szybkieg
         poruszania się po mieście. 5 lekcji po 3$ od osoby. Za każdą gracze rozwijają
         skille (akrobatyka, nawigacja) o K4 każdy.
         Szczur nazywa się John McQuensee ma 20 lat i jest na ulicy od dziecka. W
         przeciwieństwie, do innych hobo jest z NY i tu zamierza spędzić życie.
         Jest nieprzyzwoicie uczciwy i słowny jak na człowieka ulicy. Wierzy za to w
         demony duchy i inne takie legendy. Chętnie dołącza do graczy.




<<Studnia>>
            Na farmie około 6h jazdy od NY. przy małym miasteczku
            Beneton Pensylwania, Mieszka starszy miły pan. Frank Petee.
            Wrócił on na tą farmę "na emerytuę". Frama jest zaniedbana i właściwie
            jest to dom z bardzo dużym ogrodem ważywnym bardziej niż farma.
            Na farmie jest domek, szopa na narzędzia, stodoła, małe lapidarium.
            Czyli wytarte przez czas tablice na nazwiskami przodków i postawiony
            w 1810 mały grobowiec, częściowo zakopany w skarpie.
            Starszy pan zachęca by przyjść na herbatkę i takie inne, ale wyraźnie
            próbuje by gracze nie podchodzili do studni. Klamka i zawiasy od wrót
            grobowca nie są w złym stanie. Okazuje się że Frank Petee oddał ją we
            władanie siły nie czystej i tak na prawdę już nie żyje. Mówi i porusza się
            bardzo bardzo powoli. W studni jest ta siła nieczysta zaklęta. Jeśli gracze ją
            wypuszczą i poskromią, starszy pan umrze i im za to podziękuje.
            Cała ta zadyma jest spowodowana tym, że w rozpaczy po śmieci córki i żony
            usłyszał o jakiejś magi wskrzeszania i zrobił rytułał by móc w nocy rozmawiać z
            żoną. (ona nie może opuścić trumny, ale mogą rozmawiać szeptem w krypcie).
            Dla graczy dziwne są oznaki że starszy pan nie je. (może brak jedzenia poza starymi zapasami?) czy coś w te mańkę?
